added tests

diff --git a/librenms/templates/tests/test-connection.yaml b/librenms/templates/tests/test-connection.yaml
--- a/librenms/templates/tests/test-connection.yaml
+++ b/librenms/templates/tests/test-connection.yaml
@@ -1,15 +1,39 @@
-apiVersion: v1
-kind: Pod
+apiVersion: batch/v1
+kind: Job
 metadata:
-  name: "{{ include "librenms.fullname" . }}-test-connection"
-  labels:
-    {{- include "librenms.labels" . | nindent 4 }}
-  annotations:
-    "helm.sh/hook": test
+  name: mariadb-connection-test
+  namespace: {{ .Release.Namespace }}
 spec:
-  containers:
-    - name: wget
-      image: busybox
-      command: ['wget']
-      args: ['{{ include "librenms.fullname" . }}:{{ .Values.service.port }}']
-  restartPolicy: Never
+  backoffLimit: 3
+  template:
+    metadata:
+      labels:
+        app: mariadb-connection-test
+    spec:
+      restartPolicy: Never
+      containers:
+        - name: mariadb-connection-test
+          image: mysql:5.7
+          command:
+            - /bin/sh
+            - -c
+            - |
+              echo "Testing connection to MariaDB...";
+              mysql --host=mariadb --user={{ .Values.database.user }} --password={{ .Values.database.password }} --execute="SELECT 1;" {{ .Values.database.name }};
+              if [ $? -eq 0 ]; then
+                echo "Connection to MariaDB is successful!";
+                exit 0;
+              else
+                echo "Failed to connect to MariaDB.";
+                exit 1;
+              fi
+          env:
+            - name: MYSQL_HOST
+              value: "mariadb"
+            - name: MYSQL_USER
+              value: "{{ .Values.database.user }}"
+            - name: MYSQL_PASSWORD
+              value: "{{ .Values.database.password }}"
+            - name: MYSQL_DATABASE
+              value: "{{ .Values.database.name }}"
+
